name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Compile CV English
      uses: xu-cheng/latex-action@master
      with:
        root_file: cv.en.tex
        extra_packages: moderncv
    - name: Compile CV Italian
      uses: xu-cheng/latex-action@master
      with:
        root_file: cv.it.tex
        extra_packages: moderncv
    - name: Deploy on GitHub pages
      uses: JamesIves/github-pages-deploy-action@ghtoken
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: mkdir build && cp cv.it.pdf cv.en.pdf build/ 
