name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Compile LaTeX
      uses: docker://aergus/latex
      with: 
        entrypoint: /usr/bin/make
    - name: Deploy on GitHub pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
